services:
  backend:
    restart: "always"
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - ./backend/serviceAccountKey.json:/app/serviceAccountKey.json:ro
      - ./backend/.env:/app/.env:ro

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/serviceAccountKey.json
      FLASK_DEBUG: 1  

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend/front_app:/user/src/app
  #   depends_on:
  #     - backend


