services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - ./scripts:/app/scripts
    command: >
      sh -c "
        python /app/scripts/init_db.py &&
        python run.py
      "
    restart: unless-stopped


volumes:
  mysql_data:

